FROM openjdk:17-jdk-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
COPY root.crt /home/spring/.postgresql/root.crt
ENV JDBC_MOCKED_DB_URL=
ENV JDBC_COMPLAINTS_DB_URL=
ENTRYPOINT ["java","-jar","/app.jar"]