FROM golang:1.19 AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./

RUN go build -o /cui-gateway

# Base image that only contains the necessary tools to run the application
FROM gcr.io/distroless/base-debian11

WORKDIR /

# Copy the binary that has been build with the "full" base image
COPY --from=build /cui-gateway /cui-gateway

EXPOSE 3011

USER nonroot:nonroot

ENTRYPOINT ["/cui-gateway"]